// Static seed data for the Demo Organization's customer list — sourced from
// the "AFIK_Demo_Customers_100.xlsx" reference file, for demo viewing only.
// Never touches real organizations: seedDemoCustomers() (see demo.functions.ts)
// only writes into whichever org the calling (already-authenticated) user
// belongs to, and the app only lets the dedicated demo user into "Demo
// Organization" — so in practice this data is fully isolated from real customers.
export type DemoCustomerSeed = {
  companyName: string;
  tradeName: string;
  status: "active" | "inactive" | "lead";
  customerCode: string;
  companyType: string;
  companyId: string;
  industry: string;
  website: string;
};

export const DEMO_CUSTOMERS_SEED: DemoCustomerSeed[] = [
  { companyName: "Demo Company 1", tradeName: "DC001", status: "active", customerCode: "CUST-0001", companyType: "חברת שילוח", companyId: "510000001", industry: "שילוח בינלאומי", website: "https://demo1.example.com" },
  { companyName: "Demo Company 2", tradeName: "DC002", status: "lead", customerCode: "CUST-0002", companyType: "חברת בלדרות", companyId: "510000002", industry: "שילוח מקומי", website: "https://demo2.example.com" },
  { companyName: "Demo Company 3", tradeName: "DC003", status: "inactive", customerCode: "CUST-0003", companyType: "חברת לוגיסטיקה", companyId: "510000003", industry: "פארמה", website: "https://demo3.example.com" },
  { companyName: "Demo Company 4", tradeName: "DC004", status: "active", customerCode: "CUST-0004", companyType: "עמיל מכס", companyId: "510000004", industry: "שרשרת קירור", website: "https://demo4.example.com" },
  { companyName: "Demo Company 5", tradeName: "DC005", status: "lead", customerCode: "CUST-0005", companyType: "חברת פארמה", companyId: "510000005", industry: "ניסויים קליניים", website: "https://demo5.example.com" },
  { companyName: "Demo Company 6", tradeName: "DC006", status: "inactive", customerCode: "CUST-0006", companyType: "חברת ביוטכנולוגיה", companyId: "510000006", industry: "ביוטכנולוגיה", website: "https://demo6.example.com" },
  { companyName: "Demo Company 7", tradeName: "DC007", status: "active", customerCode: "CUST-0007", companyType: "יצרן ציוד רפואי", companyId: "510000007", industry: "ציוד רפואי", website: "https://demo7.example.com" },
  { companyName: "Demo Company 8", tradeName: "DC008", status: "lead", customerCode: "CUST-0008", companyType: "בית חולים", companyId: "510000008", industry: "בריאות", website: "https://demo8.example.com" },
  { companyName: "Demo Company 9", tradeName: "DC009", status: "inactive", customerCode: "CUST-0009", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000009", industry: "הפצה", website: "https://demo9.example.com" },
  { companyName: "Demo Company 10", tradeName: "DC010", status: "active", customerCode: "CUST-0010", companyType: "חברת הפצה", companyId: "510000010", industry: "אחסנה", website: "https://demo10.example.com" },
  { companyName: "Demo Company 11", tradeName: "DC011", status: "lead", customerCode: "CUST-0011", companyType: "חברת שילוח", companyId: "510000011", industry: "שילוח בינלאומי", website: "https://demo11.example.com" },
  { companyName: "Demo Company 12", tradeName: "DC012", status: "inactive", customerCode: "CUST-0012", companyType: "חברת בלדרות", companyId: "510000012", industry: "שילוח מקומי", website: "https://demo12.example.com" },
  { companyName: "Demo Company 13", tradeName: "DC013", status: "active", customerCode: "CUST-0013", companyType: "חברת לוגיסטיקה", companyId: "510000013", industry: "פארמה", website: "https://demo13.example.com" },
  { companyName: "Demo Company 14", tradeName: "DC014", status: "lead", customerCode: "CUST-0014", companyType: "עמיל מכס", companyId: "510000014", industry: "שרשרת קירור", website: "https://demo14.example.com" },
  { companyName: "Demo Company 15", tradeName: "DC015", status: "inactive", customerCode: "CUST-0015", companyType: "חברת פארמה", companyId: "510000015", industry: "ניסויים קליניים", website: "https://demo15.example.com" },
  { companyName: "Demo Company 16", tradeName: "DC016", status: "active", customerCode: "CUST-0016", companyType: "חברת ביוטכנולוגיה", companyId: "510000016", industry: "ביוטכנולוגיה", website: "https://demo16.example.com" },
  { companyName: "Demo Company 17", tradeName: "DC017", status: "lead", customerCode: "CUST-0017", companyType: "יצרן ציוד רפואי", companyId: "510000017", industry: "ציוד רפואי", website: "https://demo17.example.com" },
  { companyName: "Demo Company 18", tradeName: "DC018", status: "inactive", customerCode: "CUST-0018", companyType: "בית חולים", companyId: "510000018", industry: "בריאות", website: "https://demo18.example.com" },
  { companyName: "Demo Company 19", tradeName: "DC019", status: "active", customerCode: "CUST-0019", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000019", industry: "הפצה", website: "https://demo19.example.com" },
  { companyName: "Demo Company 20", tradeName: "DC020", status: "lead", customerCode: "CUST-0020", companyType: "חברת הפצה", companyId: "510000020", industry: "אחסנה", website: "https://demo20.example.com" },
  { companyName: "Demo Company 21", tradeName: "DC021", status: "inactive", customerCode: "CUST-0021", companyType: "חברת שילוח", companyId: "510000021", industry: "שילוח בינלאומי", website: "https://demo21.example.com" },
  { companyName: "Demo Company 22", tradeName: "DC022", status: "active", customerCode: "CUST-0022", companyType: "חברת בלדרות", companyId: "510000022", industry: "שילוח מקומי", website: "https://demo22.example.com" },
  { companyName: "Demo Company 23", tradeName: "DC023", status: "lead", customerCode: "CUST-0023", companyType: "חברת לוגיסטיקה", companyId: "510000023", industry: "פארמה", website: "https://demo23.example.com" },
  { companyName: "Demo Company 24", tradeName: "DC024", status: "inactive", customerCode: "CUST-0024", companyType: "עמיל מכס", companyId: "510000024", industry: "שרשרת קירור", website: "https://demo24.example.com" },
  { companyName: "Demo Company 25", tradeName: "DC025", status: "active", customerCode: "CUST-0025", companyType: "חברת פארמה", companyId: "510000025", industry: "ניסויים קליניים", website: "https://demo25.example.com" },
  { companyName: "Demo Company 26", tradeName: "DC026", status: "lead", customerCode: "CUST-0026", companyType: "חברת ביוטכנולוגיה", companyId: "510000026", industry: "ביוטכנולוגיה", website: "https://demo26.example.com" },
  { companyName: "Demo Company 27", tradeName: "DC027", status: "inactive", customerCode: "CUST-0027", companyType: "יצרן ציוד רפואי", companyId: "510000027", industry: "ציוד רפואי", website: "https://demo27.example.com" },
  { companyName: "Demo Company 28", tradeName: "DC028", status: "active", customerCode: "CUST-0028", companyType: "בית חולים", companyId: "510000028", industry: "בריאות", website: "https://demo28.example.com" },
  { companyName: "Demo Company 29", tradeName: "DC029", status: "lead", customerCode: "CUST-0029", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000029", industry: "הפצה", website: "https://demo29.example.com" },
  { companyName: "Demo Company 30", tradeName: "DC030", status: "inactive", customerCode: "CUST-0030", companyType: "חברת הפצה", companyId: "510000030", industry: "אחסנה", website: "https://demo30.example.com" },
  { companyName: "Demo Company 31", tradeName: "DC031", status: "active", customerCode: "CUST-0031", companyType: "חברת שילוח", companyId: "510000031", industry: "שילוח בינלאומי", website: "https://demo31.example.com" },
  { companyName: "Demo Company 32", tradeName: "DC032", status: "lead", customerCode: "CUST-0032", companyType: "חברת בלדרות", companyId: "510000032", industry: "שילוח מקומי", website: "https://demo32.example.com" },
  { companyName: "Demo Company 33", tradeName: "DC033", status: "inactive", customerCode: "CUST-0033", companyType: "חברת לוגיסטיקה", companyId: "510000033", industry: "פארמה", website: "https://demo33.example.com" },
  { companyName: "Demo Company 34", tradeName: "DC034", status: "active", customerCode: "CUST-0034", companyType: "עמיל מכס", companyId: "510000034", industry: "שרשרת קירור", website: "https://demo34.example.com" },
  { companyName: "Demo Company 35", tradeName: "DC035", status: "lead", customerCode: "CUST-0035", companyType: "חברת פארמה", companyId: "510000035", industry: "ניסויים קליניים", website: "https://demo35.example.com" },
  { companyName: "Demo Company 36", tradeName: "DC036", status: "inactive", customerCode: "CUST-0036", companyType: "חברת ביוטכנולוגיה", companyId: "510000036", industry: "ביוטכנולוגיה", website: "https://demo36.example.com" },
  { companyName: "Demo Company 37", tradeName: "DC037", status: "active", customerCode: "CUST-0037", companyType: "יצרן ציוד רפואי", companyId: "510000037", industry: "ציוד רפואי", website: "https://demo37.example.com" },
  { companyName: "Demo Company 38", tradeName: "DC038", status: "lead", customerCode: "CUST-0038", companyType: "בית חולים", companyId: "510000038", industry: "בריאות", website: "https://demo38.example.com" },
  { companyName: "Demo Company 39", tradeName: "DC039", status: "inactive", customerCode: "CUST-0039", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000039", industry: "הפצה", website: "https://demo39.example.com" },
  { companyName: "Demo Company 40", tradeName: "DC040", status: "active", customerCode: "CUST-0040", companyType: "חברת הפצה", companyId: "510000040", industry: "אחסנה", website: "https://demo40.example.com" },
  { companyName: "Demo Company 41", tradeName: "DC041", status: "lead", customerCode: "CUST-0041", companyType: "חברת שילוח", companyId: "510000041", industry: "שילוח בינלאומי", website: "https://demo41.example.com" },
  { companyName: "Demo Company 42", tradeName: "DC042", status: "inactive", customerCode: "CUST-0042", companyType: "חברת בלדרות", companyId: "510000042", industry: "שילוח מקומי", website: "https://demo42.example.com" },
  { companyName: "Demo Company 43", tradeName: "DC043", status: "active", customerCode: "CUST-0043", companyType: "חברת לוגיסטיקה", companyId: "510000043", industry: "פארמה", website: "https://demo43.example.com" },
  { companyName: "Demo Company 44", tradeName: "DC044", status: "lead", customerCode: "CUST-0044", companyType: "עמיל מכס", companyId: "510000044", industry: "שרשרת קירור", website: "https://demo44.example.com" },
  { companyName: "Demo Company 45", tradeName: "DC045", status: "inactive", customerCode: "CUST-0045", companyType: "חברת פארמה", companyId: "510000045", industry: "ניסויים קליניים", website: "https://demo45.example.com" },
  { companyName: "Demo Company 46", tradeName: "DC046", status: "active", customerCode: "CUST-0046", companyType: "חברת ביוטכנולוגיה", companyId: "510000046", industry: "ביוטכנולוגיה", website: "https://demo46.example.com" },
  { companyName: "Demo Company 47", tradeName: "DC047", status: "lead", customerCode: "CUST-0047", companyType: "יצרן ציוד רפואי", companyId: "510000047", industry: "ציוד רפואי", website: "https://demo47.example.com" },
  { companyName: "Demo Company 48", tradeName: "DC048", status: "inactive", customerCode: "CUST-0048", companyType: "בית חולים", companyId: "510000048", industry: "בריאות", website: "https://demo48.example.com" },
  { companyName: "Demo Company 49", tradeName: "DC049", status: "active", customerCode: "CUST-0049", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000049", industry: "הפצה", website: "https://demo49.example.com" },
  { companyName: "Demo Company 50", tradeName: "DC050", status: "lead", customerCode: "CUST-0050", companyType: "חברת הפצה", companyId: "510000050", industry: "אחסנה", website: "https://demo50.example.com" },
  { companyName: "Demo Company 51", tradeName: "DC051", status: "inactive", customerCode: "CUST-0051", companyType: "חברת שילוח", companyId: "510000051", industry: "שילוח בינלאומי", website: "https://demo51.example.com" },
  { companyName: "Demo Company 52", tradeName: "DC052", status: "active", customerCode: "CUST-0052", companyType: "חברת בלדרות", companyId: "510000052", industry: "שילוח מקומי", website: "https://demo52.example.com" },
  { companyName: "Demo Company 53", tradeName: "DC053", status: "lead", customerCode: "CUST-0053", companyType: "חברת לוגיסטיקה", companyId: "510000053", industry: "פארמה", website: "https://demo53.example.com" },
  { companyName: "Demo Company 54", tradeName: "DC054", status: "inactive", customerCode: "CUST-0054", companyType: "עמיל מכס", companyId: "510000054", industry: "שרשרת קירור", website: "https://demo54.example.com" },
  { companyName: "Demo Company 55", tradeName: "DC055", status: "active", customerCode: "CUST-0055", companyType: "חברת פארמה", companyId: "510000055", industry: "ניסויים קליניים", website: "https://demo55.example.com" },
  { companyName: "Demo Company 56", tradeName: "DC056", status: "lead", customerCode: "CUST-0056", companyType: "חברת ביוטכנולוגיה", companyId: "510000056", industry: "ביוטכנולוגיה", website: "https://demo56.example.com" },
  { companyName: "Demo Company 57", tradeName: "DC057", status: "inactive", customerCode: "CUST-0057", companyType: "יצרן ציוד רפואי", companyId: "510000057", industry: "ציוד רפואי", website: "https://demo57.example.com" },
  { companyName: "Demo Company 58", tradeName: "DC058", status: "active", customerCode: "CUST-0058", companyType: "בית חולים", companyId: "510000058", industry: "בריאות", website: "https://demo58.example.com" },
  { companyName: "Demo Company 59", tradeName: "DC059", status: "lead", customerCode: "CUST-0059", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000059", industry: "הפצה", website: "https://demo59.example.com" },
  { companyName: "Demo Company 60", tradeName: "DC060", status: "inactive", customerCode: "CUST-0060", companyType: "חברת הפצה", companyId: "510000060", industry: "אחסנה", website: "https://demo60.example.com" },
  { companyName: "Demo Company 61", tradeName: "DC061", status: "active", customerCode: "CUST-0061", companyType: "חברת שילוח", companyId: "510000061", industry: "שילוח בינלאומי", website: "https://demo61.example.com" },
  { companyName: "Demo Company 62", tradeName: "DC062", status: "lead", customerCode: "CUST-0062", companyType: "חברת בלדרות", companyId: "510000062", industry: "שילוח מקומי", website: "https://demo62.example.com" },
  { companyName: "Demo Company 63", tradeName: "DC063", status: "inactive", customerCode: "CUST-0063", companyType: "חברת לוגיסטיקה", companyId: "510000063", industry: "פארמה", website: "https://demo63.example.com" },
  { companyName: "Demo Company 64", tradeName: "DC064", status: "active", customerCode: "CUST-0064", companyType: "עמיל מכס", companyId: "510000064", industry: "שרשרת קירור", website: "https://demo64.example.com" },
  { companyName: "Demo Company 65", tradeName: "DC065", status: "lead", customerCode: "CUST-0065", companyType: "חברת פארמה", companyId: "510000065", industry: "ניסויים קליניים", website: "https://demo65.example.com" },
  { companyName: "Demo Company 66", tradeName: "DC066", status: "inactive", customerCode: "CUST-0066", companyType: "חברת ביוטכנולוגיה", companyId: "510000066", industry: "ביוטכנולוגיה", website: "https://demo66.example.com" },
  { companyName: "Demo Company 67", tradeName: "DC067", status: "active", customerCode: "CUST-0067", companyType: "יצרן ציוד רפואי", companyId: "510000067", industry: "ציוד רפואי", website: "https://demo67.example.com" },
  { companyName: "Demo Company 68", tradeName: "DC068", status: "lead", customerCode: "CUST-0068", companyType: "בית חולים", companyId: "510000068", industry: "בריאות", website: "https://demo68.example.com" },
  { companyName: "Demo Company 69", tradeName: "DC069", status: "inactive", customerCode: "CUST-0069", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000069", industry: "הפצה", website: "https://demo69.example.com" },
  { companyName: "Demo Company 70", tradeName: "DC070", status: "active", customerCode: "CUST-0070", companyType: "חברת הפצה", companyId: "510000070", industry: "אחסנה", website: "https://demo70.example.com" },
  { companyName: "Demo Company 71", tradeName: "DC071", status: "lead", customerCode: "CUST-0071", companyType: "חברת שילוח", companyId: "510000071", industry: "שילוח בינלאומי", website: "https://demo71.example.com" },
  { companyName: "Demo Company 72", tradeName: "DC072", status: "inactive", customerCode: "CUST-0072", companyType: "חברת בלדרות", companyId: "510000072", industry: "שילוח מקומי", website: "https://demo72.example.com" },
  { companyName: "Demo Company 73", tradeName: "DC073", status: "active", customerCode: "CUST-0073", companyType: "חברת לוגיסטיקה", companyId: "510000073", industry: "פארמה", website: "https://demo73.example.com" },
  { companyName: "Demo Company 74", tradeName: "DC074", status: "lead", customerCode: "CUST-0074", companyType: "עמיל מכס", companyId: "510000074", industry: "שרשרת קירור", website: "https://demo74.example.com" },
  { companyName: "Demo Company 75", tradeName: "DC075", status: "inactive", customerCode: "CUST-0075", companyType: "חברת פארמה", companyId: "510000075", industry: "ניסויים קליניים", website: "https://demo75.example.com" },
  { companyName: "Demo Company 76", tradeName: "DC076", status: "active", customerCode: "CUST-0076", companyType: "חברת ביוטכנולוגיה", companyId: "510000076", industry: "ביוטכנולוגיה", website: "https://demo76.example.com" },
  { companyName: "Demo Company 77", tradeName: "DC077", status: "lead", customerCode: "CUST-0077", companyType: "יצרן ציוד רפואי", companyId: "510000077", industry: "ציוד רפואי", website: "https://demo77.example.com" },
  { companyName: "Demo Company 78", tradeName: "DC078", status: "inactive", customerCode: "CUST-0078", companyType: "בית חולים", companyId: "510000078", industry: "בריאות", website: "https://demo78.example.com" },
  { companyName: "Demo Company 79", tradeName: "DC079", status: "active", customerCode: "CUST-0079", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000079", industry: "הפצה", website: "https://demo79.example.com" },
  { companyName: "Demo Company 80", tradeName: "DC080", status: "lead", customerCode: "CUST-0080", companyType: "חברת הפצה", companyId: "510000080", industry: "אחסנה", website: "https://demo80.example.com" },
  { companyName: "Demo Company 81", tradeName: "DC081", status: "inactive", customerCode: "CUST-0081", companyType: "חברת שילוח", companyId: "510000081", industry: "שילוח בינלאומי", website: "https://demo81.example.com" },
  { companyName: "Demo Company 82", tradeName: "DC082", status: "active", customerCode: "CUST-0082", companyType: "חברת בלדרות", companyId: "510000082", industry: "שילוח מקומי", website: "https://demo82.example.com" },
  { companyName: "Demo Company 83", tradeName: "DC083", status: "lead", customerCode: "CUST-0083", companyType: "חברת לוגיסטיקה", companyId: "510000083", industry: "פארמה", website: "https://demo83.example.com" },
  { companyName: "Demo Company 84", tradeName: "DC084", status: "inactive", customerCode: "CUST-0084", companyType: "עמיל מכס", companyId: "510000084", industry: "שרשרת קירור", website: "https://demo84.example.com" },
  { companyName: "Demo Company 85", tradeName: "DC085", status: "active", customerCode: "CUST-0085", companyType: "חברת פארמה", companyId: "510000085", industry: "ניסויים קליניים", website: "https://demo85.example.com" },
  { companyName: "Demo Company 86", tradeName: "DC086", status: "lead", customerCode: "CUST-0086", companyType: "חברת ביוטכנולוגיה", companyId: "510000086", industry: "ביוטכנולוגיה", website: "https://demo86.example.com" },
  { companyName: "Demo Company 87", tradeName: "DC087", status: "inactive", customerCode: "CUST-0087", companyType: "יצרן ציוד רפואי", companyId: "510000087", industry: "ציוד רפואי", website: "https://demo87.example.com" },
  { companyName: "Demo Company 88", tradeName: "DC088", status: "active", customerCode: "CUST-0088", companyType: "בית חולים", companyId: "510000088", industry: "בריאות", website: "https://demo88.example.com" },
  { companyName: "Demo Company 89", tradeName: "DC089", status: "lead", customerCode: "CUST-0089", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000089", industry: "הפצה", website: "https://demo89.example.com" },
  { companyName: "Demo Company 90", tradeName: "DC090", status: "inactive", customerCode: "CUST-0090", companyType: "חברת הפצה", companyId: "510000090", industry: "אחסנה", website: "https://demo90.example.com" },
  { companyName: "Demo Company 91", tradeName: "DC091", status: "active", customerCode: "CUST-0091", companyType: "חברת שילוח", companyId: "510000091", industry: "שילוח בינלאומי", website: "https://demo91.example.com" },
  { companyName: "Demo Company 92", tradeName: "DC092", status: "lead", customerCode: "CUST-0092", companyType: "חברת בלדרות", companyId: "510000092", industry: "שילוח מקומי", website: "https://demo92.example.com" },
  { companyName: "Demo Company 93", tradeName: "DC093", status: "inactive", customerCode: "CUST-0093", companyType: "חברת לוגיסטיקה", companyId: "510000093", industry: "פארמה", website: "https://demo93.example.com" },
  { companyName: "Demo Company 94", tradeName: "DC094", status: "active", customerCode: "CUST-0094", companyType: "עמיל מכס", companyId: "510000094", industry: "שרשרת קירור", website: "https://demo94.example.com" },
  { companyName: "Demo Company 95", tradeName: "DC095", status: "lead", customerCode: "CUST-0095", companyType: "חברת פארמה", companyId: "510000095", industry: "ניסויים קליניים", website: "https://demo95.example.com" },
  { companyName: "Demo Company 96", tradeName: "DC096", status: "inactive", customerCode: "CUST-0096", companyType: "חברת ביוטכנולוגיה", companyId: "510000096", industry: "ביוטכנולוגיה", website: "https://demo96.example.com" },
  { companyName: "Demo Company 97", tradeName: "DC097", status: "active", customerCode: "CUST-0097", companyType: "יצרן ציוד רפואי", companyId: "510000097", industry: "ציוד רפואי", website: "https://demo97.example.com" },
  { companyName: "Demo Company 98", tradeName: "DC098", status: "lead", customerCode: "CUST-0098", companyType: "בית חולים", companyId: "510000098", industry: "בריאות", website: "https://demo98.example.com" },
  { companyName: "Demo Company 99", tradeName: "DC099", status: "inactive", customerCode: "CUST-0099", companyType: "מחסן לוגיסטי (3PL)", companyId: "510000099", industry: "הפצה", website: "https://demo99.example.com" },
  { companyName: "Demo Company 100", tradeName: "DC100", status: "active", customerCode: "CUST-0100", companyType: "חברת הפצה", companyId: "510000100", industry: "אחסנה", website: "https://demo100.example.com" },
];
