-- Seed lookup_agents with a starter list of pharma/life-science freight
-- forwarding and courier agents (global rows, organization_id NULL).
-- Requested by the user to populate the "סוכן" (agent) picker.

INSERT INTO public.lookup_agents (code, name, name_en, sort_order, metadata) VALUES
  ('WORLD_COURIER', 'World Courier', 'World Courier', 1, '{"country": "USA", "specialty": "Clinical Trials, Pharma", "website": "https://www.worldcourier.com"}'),
  ('QUICKSTAT', 'QuickSTAT', 'QuickSTAT', 2, '{"country": "USA", "specialty": "Time Critical, Pharma", "website": "https://www.quickstat.aero"}'),
  ('MARKEN', 'Marken', 'Marken', 3, '{"country": "UK", "specialty": "Clinical Trials", "website": "https://www.marken.com"}'),
  ('KUEHNE_NAGEL_HC', 'Kuehne+Nagel Healthcare', 'Kuehne+Nagel Healthcare', 4, '{"country": "Switzerland", "specialty": "Healthcare Logistics", "website": "https://home.kuehne-nagel.com"}'),
  ('DHL_HEALTH', 'DHL Health Logistics', 'DHL Health Logistics', 5, '{"country": "Germany", "specialty": "GDP, Pharma", "website": "https://www.dhl.com"}'),
  ('DSV_HEALTHCARE', 'DSV Healthcare', 'DSV Healthcare', 6, '{"country": "Denmark", "specialty": "Healthcare", "website": "https://www.dsv.com"}'),
  ('CEVA_HEALTHCARE', 'CEVA Healthcare', 'CEVA Healthcare', 7, '{"country": "France", "specialty": "Healthcare", "website": "https://www.cevalogistics.com"}'),
  ('EXPEDITORS_HC', 'Expeditors Healthcare', 'Expeditors Healthcare', 8, '{"country": "USA", "specialty": "BioPharma", "website": "https://www.expeditors.com"}'),
  ('GEODIS_HEALTHCARE', 'GEODIS Healthcare', 'GEODIS Healthcare', 9, '{"country": "France", "specialty": "Healthcare", "website": "https://www.geodis.com"}'),
  ('UPS_HEALTHCARE', 'UPS Healthcare', 'UPS Healthcare', 10, '{"country": "USA", "specialty": "Healthcare", "website": "https://www.ups.com"}'),
  ('FEDEX_CUSTOM_CRITICAL', 'FedEx Custom Critical', 'FedEx Custom Critical', 11, '{"country": "USA", "specialty": "Critical Shipments", "website": "https://www.fedex.com"}'),
  ('DB_SCHENKER_HC', 'DB Schenker Healthcare', 'DB Schenker Healthcare', 12, '{"country": "Germany", "specialty": "Healthcare", "website": "https://www.dbschenker.com"}'),
  ('HELLMANN_HEALTHCARE', 'Hellmann Healthcare', 'Hellmann Healthcare', 13, '{"country": "Germany", "specialty": "Healthcare", "website": "https://www.hellmann.com"}'),
  ('NIPPON_EXPRESS', 'Nippon Express', 'Nippon Express', 14, '{"country": "Japan", "specialty": "Healthcare", "website": "https://www.nipponexpress.com"}'),
  ('YUSEN_LOGISTICS', 'Yusen Logistics', 'Yusen Logistics', 15, '{"country": "Japan", "specialty": "Healthcare", "website": "https://www.yusen-logistics.com"}'),
  ('KWE', 'Kintetsu World Express', 'Kintetsu World Express', 16, '{"country": "Japan", "specialty": "Air Freight", "website": "https://www.kwe.com"}'),
  ('SCAN_GLOBAL', 'Scan Global Logistics', 'Scan Global Logistics', 17, '{"country": "Denmark", "specialty": "Time Critical", "website": "https://www.scangl.com"}'),
  ('RHENUS', 'Rhenus Logistics', 'Rhenus Logistics', 18, '{"country": "Germany", "specialty": "Healthcare", "website": "https://www.rhenus.group"}'),
  ('DACHSER', 'DACHSER', 'DACHSER', 19, '{"country": "Germany", "specialty": "Air & Sea", "website": "https://www.dachser.com"}'),
  ('LOGWIN', 'Logwin', 'Logwin', 20, '{"country": "Luxembourg", "specialty": "Air Freight", "website": "https://www.logwin-logistics.com"}'),
  ('SAVINO_DEL_BENE', 'Savino Del Bene', 'Savino Del Bene', 21, '{"country": "Italy", "specialty": "Air & Sea", "website": "https://www.savinodelbene.com"}'),
  ('CH_ROBINSON', 'C.H. Robinson', 'C.H. Robinson', 22, '{"country": "USA", "specialty": "Global Forwarding", "website": "https://www.chrobinson.com"}'),
  ('MAERSK_LOGISTICS', 'Maersk Logistics', 'Maersk Logistics', 23, '{"country": "Denmark", "specialty": "Integrated Logistics", "website": "https://www.maersk.com"}'),
  ('LX_PANTOS', 'LX Pantos', 'LX Pantos', 24, '{"country": "South Korea", "specialty": "Global Logistics", "website": "https://www.lxpantos.com"}'),
  ('SINOTRANS', 'Sinotrans', 'Sinotrans', 25, '{"country": "China", "specialty": "Global Freight", "website": "https://www.sinotrans.com"}'),
  ('OOCL_LOGISTICS', 'OOCL Logistics', 'OOCL Logistics', 26, '{"country": "Hong Kong", "specialty": "Ocean & Air", "website": "https://www.oocllogistics.com"}'),
  ('TOLL_GROUP', 'Toll Group', 'Toll Group', 27, '{"country": "Australia", "specialty": "Healthcare", "website": "https://www.tollgroup.com"}'),
  ('MAINFREIGHT', 'Mainfreight', 'Mainfreight', 28, '{"country": "New Zealand", "specialty": "Global Logistics", "website": "https://www.mainfreight.com"}'),
  ('AIT_WORLDWIDE', 'AIT Worldwide Logistics', 'AIT Worldwide Logistics', 29, '{"country": "USA", "specialty": "Life Sciences", "website": "https://www.aitworldwide.com"}'),
  ('SEKO_LOGISTICS', 'SEKO Logistics', 'SEKO Logistics', 30, '{"country": "USA", "specialty": "Time Critical", "website": "https://www.sekologistics.com"}'),
  ('AIR_CHARTER_SERVICE', 'Air Charter Service', 'Air Charter Service', 31, '{"country": "UK", "specialty": "Charter", "website": "https://www.aircharterservice.com"}'),
  ('CHAPMAN_FREEBORN', 'Chapman Freeborn', 'Chapman Freeborn', 32, '{"country": "UK", "specialty": "Air Charter", "website": "https://www.chapmanfreeborn.aero"}'),
  ('TIME_MATTERS', 'time:matters', 'time:matters', 33, '{"country": "Germany", "specialty": "Emergency Logistics", "website": "https://www.time-matters.com"}'),
  ('MNX_GLOBAL', 'MNX Global Logistics', 'MNX Global Logistics', 34, '{"country": "USA", "specialty": "Medical Logistics", "website": "https://www.mnx.com"}'),
  ('CRYOPORT', 'Cryoport Systems', 'Cryoport Systems', 35, '{"country": "USA", "specialty": "Cryogenic Logistics", "website": "https://www.cryoport.com"}'),
  ('BIOCARE_SD', 'BioCare SD', 'BioCare SD', 36, '{"country": "USA", "specialty": "Life Science", "website": "https://www.biocaresd.com"}'),
  ('BIOCAIR', 'Biocair', 'Biocair', 37, '{"country": "UK", "specialty": "Life Sciences", "website": "https://www.biocair.com"}'),
  ('MOVIANTO', 'Movianto', 'Movianto', 38, '{"country": "Germany", "specialty": "Healthcare Distribution", "website": "https://www.movianto.com"}'),
  ('FISHER_CLINICAL', 'Fisher Clinical Services', 'Fisher Clinical Services', 39, '{"country": "USA", "specialty": "Clinical Logistics", "website": "https://www.fisherclinicalservices.com"}'),
  ('ALMAC_CLINICAL', 'Almac Clinical Services', 'Almac Clinical Services', 40, '{"country": "UK", "specialty": "Clinical Supply", "website": "https://www.almacgroup.com"}'),
  ('PAREXEL', 'Parexel Logistics', 'Parexel Logistics', 41, '{"country": "USA", "specialty": "Clinical Research", "website": "https://www.parexel.com"}'),
  ('CATALENT', 'Catalent Clinical Supply', 'Catalent Clinical Supply', 42, '{"country": "USA", "specialty": "Clinical Supply", "website": "https://www.catalent.com"}'),
  ('PCI_PHARMA', 'PCI Pharma Services', 'PCI Pharma Services', 43, '{"country": "USA", "specialty": "Clinical Supply", "website": "https://www.pciservices.com"}'),
  ('THERMO_FISHER', 'Thermo Fisher Logistics', 'Thermo Fisher Logistics', 44, '{"country": "USA", "specialty": "Life Sciences", "website": "https://www.thermofisher.com"}'),
  ('UNILODE', 'Unilode Aviation Solutions', 'Unilode Aviation Solutions', 45, '{"country": "Switzerland", "specialty": "Air Cargo ULD", "website": "https://www.unilode.com"}'),
  ('AGILITY_LOGISTICS', 'Agility Logistics', 'Agility Logistics', 46, '{"country": "Kuwait", "specialty": "Integrated Logistics", "website": "https://www.agility.com"}'),
  ('FLEXPORT', 'Flexport', 'Flexport', 47, '{"country": "USA", "specialty": "Digital Freight", "website": "https://www.flexport.com"}'),
  ('KERRY_LOGISTICS', 'Kerry Logistics Network', 'Kerry Logistics Network', 48, '{"country": "Hong Kong", "specialty": "Global Logistics", "website": "https://www.kln.com"}'),
  ('BLUE_WATER_SHIPPING', 'Blue Water Shipping', 'Blue Water Shipping', 49, '{"country": "Denmark", "specialty": "Project Logistics", "website": "https://www.bws.net"}'),
  ('BDP_INTERNATIONAL', 'BDP International', 'BDP International', 50, '{"country": "USA", "specialty": "Chemical & Healthcare", "website": "https://www.bdpinternational.com"}');
